# 启动脚本
# java -jar eureka-server-0.0.1-SNAPSHOT.jar --spring.profiles.active=1111
server:
  port: 1111

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:1112/eureka/
